services:
  notebook:
    build: 
      context: example
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./example/Notebooks:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"
  iris:
    image: intersystemsdc/iris-community:preview
    command: 
      - --check-caps false
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    ports:
      - 52773
      - 1972