services:
  notebook:
    build: 
      context: example
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./example/Notebooks/Vanilla:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"
  iris:
    build: 
      context: iris
      dockerfile: Dockerfile
    volumes:
      - ./example/Notebooks/Embedded:/irisdev/app/src/Notebooks
      - ./.:/irisdev/app/
    ports:
      - 52773
      - 1972
      - 8889:8888